# FROM node:18-alpine

# WORKDIR /app

# RUN npm install -g nodemon

# COPY package*.json ./
# RUN npm install

# COPY . .

# EXPOSE 3000

# CMD ["npx", "nodemon", "--watch", "src", "--ext", "ts", "--exec", "node --no-warnings --loader ts-node/esm src/server.ts"]


FROM node:18-alpine

WORKDIR /app

RUN npm install -g nodemon

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npx", "nodemon", "-L", "--watch", "src", "--ext", "ts", "--exec", "node --no-warnings --loader ts-node/esm src/server.ts"]
